---
- name: Install certbot
  community.general.openbsd_pkg:
    name:
      - certbot
    state: present

- name: Check if certs are already installed
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ reverse_proxy_server_name }}/fullchain.pem
  register: certchain

- name: Ensure nginx is stopped if certs need to be installed
  ansible.builtin.debug: msg=''
  notify: stop nginx
  when: certchain.stat.exists is not defined or not certchain.stat.exists

- name: Obtain and install certificate using certbot
  ansible.builtin.command:
    cmd: >
      certbot --standalone certonly -d {{ reverse_proxy_server_name }}
      --non-interactive --agree-tos -m {{ certbot_email }}
  notify: start nginx
  when: certchain.stat.exists is not defined or not certchain.stat.exists
