---
- name: Install nginx
  community.general.openbsd_pkg:
    name: nginx
    state: present

- name: Ensure nginx config directory exists
  ansible.builtin.file:
    path: /etc/nginx/http.d
    state: directory
    owner: root
    group: wheel
    mode: 0644

- name: Setup nginx.conf
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: 0644

- name: Setup proxy_pass.conf
  ansible.builtin.template:
    src: templates/proxy_pass.conf.j2
    dest: /etc/nginx/http.d/proxy_pass.conf
    owner: root
    group: wheel
    mode: 0644

- name: Enable nginx service
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
