---
- name: Install tailscale
  openbsd_pkg:
    name: tailscale
    state: present

- name: Create tailscale user group
  group:
    name: tailscale
    state: present

- name: Create tailscale user
  user:
    name: tailscale
    group: tailscale
    password: "{{ user_passwd | password_hash('bcrypt') }}"
    shell: "{{ user_shell }}"

- name: Authenticate tailscale
  command: doas tailscale tailscale up --authkey="{{ tailscale_authkey }}"
