---
- name: restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: reload pf.conf
  ansible.builtin.command: pfctl -f /etc/pf.conf
