---
- name: Configure /etc/doas.conf
  ansible.builtin.copy:
    dest: /etc/doas.conf
    content: "{{ doas }}"
    owner: root
    group: wheel
    mode: 0644

- name: Create regular user group
  ansible.builtin.group:
    name: "{{ user }}"
    state: present

- name: Create regular user with doas privileges
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ user }}"
    password: "{{ user_passwd | password_hash('bcrypt') }}"
    groups: wheel
    append: true
    shell: "{{ user_shell }}"

- name: Ensure authorized keys for remote user is installed
  ansible.posix.authorized_key:
    user: "{{ user }}"
    key: "{{ ssh_pub_key }}"

- name: Ensure authorized key for root user is installed
  ansible.posix.authorized_key:
    user: root
    key: "{{ ssh_pub_key }}"

- name: Set SSH port number
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'Port '
    line: 'Port {{ ssh_port }}'
    state: present
  notify:
    - restart sshd

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify:
    - restart sshd

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify:
    - restart sshd

- name: Configure pf firewall
  ansible.builtin.template:
    src: templates/pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600
  notify:
    - reload pf.conf
