---
- name: Set timezone
  community.general.timezone:
    name: "{{ tmzone }}"
  notify:
    - restart cron

- name: Apply all available system patches
  ansible.builtin.command: syspatch
  register: syspatch
  failed_when: syspatch.rc != 0 and syspatch.rc != 2
  changed_when: syspatch.rc == 0

- name: Reboot the server if needed
  ansible.builtin.reboot:
    msg: Server reboot triggered by syspatch updates
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 15
    test_command: whoami
  when: syspatch.rc == 0

- name: Update all packages
  ansible.builtin.command: pkg_add -u

- name: Install a base set of software packages
  community.general.openbsd_pkg:
    name:
      - curl
      - git
      - htop
      - pwgen
      - rsync--
      - vim--no_x11
    state: present
